version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aezakmi

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "80:80"
    links:
      - mysql:dp
    depends_on:
      - mysql
