version: '3'

services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aezakmi

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "80:80"
    links:
      - mysql:db
    depends_on:
      - mysql

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: aezakmi
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}
